version: 2.1

orbs:
   node: circleci/node@4.7

jobs:
   devopsProject3year:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
         name: install dependecies - NPM packages
         command: npm install
      - run:
         name: run eslint
         command: npm run eslint
      - run:
         name: run tests
         command: npm run test
      - run:
         name: deploy to service
         command: curl "https://api.render.com/deploy/srv-XXYYZZ?key=AABBCC&ref=baaa339926cb474b61c1f0e6297b024eaa09ac7d"

 

workflows:
  examples-workflows:
    jobs:
      - devopsProject3year
