version: 2.1

orbs:
   node: circleci/node@4.7

jobs:
   devopsProject3year:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
         name: install dependecies - NPM packages
         command: npm install
 

workflows:
  examples-workflows:
    jobs:
      - devopsProject3year
